benchmark: specify type to avoid TSError
When I run benchmark, I faced TSError below:

```sh
$ npm run benchmark

> typescript-json@3.1.1 benchmark
> node benchmark/index.js

/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
benchmark/internal/AssertBenchmarker.ts:36:33 - error TS2538: Type 'undefined' cannot be used as an index type.

36                 (output as any)[elem.name] = elem.count / elem.times.elapsed;
                                   ~~~~~~~~~

    at createTSError (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at require.extensions.<computed> (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:1621:12)
    at Object.require.extensions.<computed> [as .ts] (/home/ubuntu/typescript-json/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  diagnosticCodes: [ 2538 ]
}
```

I can run benchmark after specifying type 'string'.